# vim: ft=yaml tabstop=2 shiftwidth=2 expandtab
---

- hosts: localhost
  pre_tasks:
    - name: Check for tower_cli configuration
      stat:
        path: "{{ ansible_env.HOME }}/.tower_cli.cfg"
      register: tower_cli_cfg

    - name: Fail if tower_cli configuration doesn't exist
      fail:
        msg: "You need to configure Tower CLI in ~/.tower_cli.cfg"
      when: not tower_cli_cfg.stat.exists

  tasks:
    - name: Configure SCM Credential
      tower_credential:
        name: Git
        description: Git default credential
        organization: null
        kind: scm
        tower_verify_ssl: False

    - name: Configure projects
      tower_project:
        name: "openstack-builder-testing"
        organization: Default
        state: present
        scm_type: git
        scm_url: "https://github.com/leifmadsen/openstack-inventory-builder.git"
        scm_branch: master
        scm_clean: yes
        #scm_credential: Git
        scm_delete_on_update: yes
        scm_update_on_launch: yes
        tower_verify_ssl: False

      #    - name: Configure credentials

      #    - name: Configure inventories

      #    - name: Configure templates
